-<?php
 -
 -namespace TheKnightGamer\KingdomWar;
 -
 -use pocketmine\plugin\PluginBase;
 -
 -class Main extends PluginBase{
 -
 +author: TheKnightGamer
 +api: [1.14.0]
 +version: 1.0.0
  main: tkg\game\KingdomWar\KWMain
  commands: 
  kw:
   description: "Start TheKnightGamer Kingdom War plugin"
   permission: tkg.kw
 permissions: 
 tkg.kw:
     description: "Kingdom WarMini-game Plugin"
     default: true
     children:
       tkg.kw.command:
         description: "Allows use all KW commands."
         default: true
         children:
           tkg.kw.command.home:
             description: "Allow use of [home] command"
             default: true
           tkg.kw.command.start:
             description: "Allows use of [start]commands"
             default: true            
           tkg.kw.command.stop:
             description: "Allows use of [stop] commands"
             default: true
